# Generated by Django 3.2.6 on 2021-09-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_trainingset_creator'),
        ('users', '0002_auto_20210927_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_training_set',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainingset'),
        ),
    ]
