version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'signs'
      POSTGRES_USER: 'phdk'
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_ROOT_PASSWORD: "${DB_PASSWORD}"
      DEBUG: 1
    networks:
      - database_network

  web:
    build: .
    image: app-image
    restart: always
    volumes:
      - .:/code
      - static_volume:/opt/services/signs/static
      - media_volume:/opt/services/signs/meda
    depends_on:
      - db
    networks:
      - database_network
    env_file:
      - .env
    environment:
      - DEBUG=1

networks:
  database_network:
    driver: bridge

volumes:
  db:
  static_volume:
  media_volume:
