# Generated by Django 3.2.6 on 2021-09-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_familiarity_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingset',
            old_name='user',
            new_name='creator',
        ),
    ]
