# Generated by Django 3.2.6 on 2021-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_trainingset_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticatom',
            name='external_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
