# Generated by Django 3.2.6 on 2021-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20210927_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'semanticatom',
            name = 'external_id',
            field = models.IntegerField(unique = True),
        ),
        migrations.AlterField(
            model_name = 'semanticatom',
            name = 'meaning',
            field = models.CharField(max_length = 255, unique = True),
        ),
    ]
