# Generated by Django 3.2.6 on 2021-09-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210927_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='external_id',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='sign',
            name='thumbnail_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
