# Generated by Django 3.2.6 on 2021-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210927_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingset',
            name='size',
        ),
        migrations.AddField(
            model_name='trainingset',
            name='name',
            field=models.TextField(default='cool set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingset',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
